version: '3.3'

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - cms_net

  iiitb_cms_fe:
    image: keerthisree/cms_fe_img:latest
    container_name: fe_container
    build: /home/keerthi/Desktop/2ndSem/SPE/MajorProject/IIITB_CMS_FE/.
    ports:
      - "4300:80"
    links:
      - app
    networks:
      - cms_net

  app:
    image: keerthisree/cms_be_img:latest
    depends_on:
      - mysqldb
    container_name: be_container
    build: .
    expose:
      - "8030"
    restart: on-failure
    env_file: .env
    ports:
      - "8030:8030"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    volumes:
      - .m2:/root/.m2
    networks:
      - cms_net
    stdin_open: true
    tty: true
volumes:
 db:
networks:
  cms_net:
    driver: bridge




#
#services:
#  #service 1: definition of mysql database
#  mysqldb:
#    image: mysql:

#    container_name: mysqldb
#    env_file:
#      - .env
#    environment:
#      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#      - MYSQL_DATABASE= $MYSQLDB_DATABASE
#    ports:
#      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#    networks:
#      - cms_net
#    restart: unless-stopped
#
#  #service 2
#  iiitb_cms_fe:
#    image: cms_fe_img
#    container_name: fe_container
#    build: /home/keerthi/Desktop/2ndSem/SPE/MajorProject/IIITB_CMS_FE/.
#    ports:
#      - "4200:4200"
#    links:
#      - iiitb_cms_be
#    networks:
#      - cms_net
#
#  #service 3: definition of your spring-boot app
#
#  iiitb_cms_be:                          #it is just a name, which will be used only in this file.
#    image: app                 #name of the image after dockerfile executes
#    container_name: be_container    #name of the container created from docker image
#    build:
#      context: .                          #docker file path (. means root directory)
#      dockerfile: Dockerfile              #docker file name
#    ports:
#      - "8030:8030"                      #docker containter port with your os port
#    restart: always
#    depends_on:                           #define dependencies of this app
#      - mysqldb                               #dependency name (which is defined with this name 'db' in this file earlier)
#    environment:
#      SPRING_APPLICATION_JSON: '{
#            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3307/IIITB_CMS_DB?useSSL=false",
#            "spring.datasource.username" : "root",
#            "spring.datasource.password" : "password",
#            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8InnoDBDialect",
#            "spring.jpa.hibernate.ddl-auto" : "update"
#          }'
#    networks:
#      - cms_net
#
#networks:
#  cms_net:
#    driver: bridge